model:
  name: "NousResearch/Llama-3.2-1B"
  device: "cuda"  # or "cpu"
  max_length: 200
  num_ground_truths: 1
  temperature: 0.7
  top_p: 0.9

privacy:
  enabled: true
  prohibited_data_types_patterns:
    sensitive_information:
      - "\\b\\d{3}-\\d{2}-\\d{4}\\b"  # SSN
      - "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}\\b"  # Email
      - "\\b\\d{4}[-\\s]?\\d{4}[-\\s]?\\d{4}[-\\s]?\\d{4}\\b"  # Credit Card
    financial_data:
      - "\\$\\d+(\\.\\d{2})?"  # Financial amounts
      - "\\b\\d{3}-\\d{2}-\\d{4}\\b"  # Duplicate for demonstration
  replacement_strings:
    sensitive_information: "[REDACTED SENSITIVE INFORMATION]"
    financial_data: "[REDACTED FINANCIAL DATA]"

cache:
  enabled: true
  cache_dir: "./cache/"
  max_cache_size: 1000  # Number of entries

logging:
  level: "INFO"
  log_file: "hype.log"

database:
  type: "sqlite"  # or "postgresql", etc.
  connection_string: "sqlite:///./user_profiles.db"

trend_analyzer:
  llama_model_name: "NousResearch/Llama-3.2-1B"  # Model name for Llama tokenizer
  spacy_model: "en_core_web_sm"  # SpaCy model for entity recognition
  top_n_keywords: 10  # Number of top trends (tokens and entities) to return
  entity_types: ['PERSON', 'ORG', 'GPE', 'DATE', 'EVENT']  # Types of entities to track
